#ifndef OPERATION_H
#define OPERATION_H

#define REGIST_CMD_ADDR 1
#define REGIST_VOICE_ADDR 2
#define GET_CMD_ADDR 3
#define GET_VOICE_ADDR 4
#define REGIST_REWO 5
#define NOTIFY_NAT_CMD 6
#define NOTIFY_NAT_VOICE 7
#define LOGIN_PUB_KEY 11
#define LOGIN_RESULT 12
#define LOGIN_PASSWORD 13
#define NOTIFY_UPDATE_CONFIG 15
#define BROADCAST_UPDATE_APP 16

#endif // OPERATION_H
