/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class worehov_android_voip_Speex2 */

#ifndef _Included_worehov_android_voip_Speex2
#define _Included_worehov_android_voip_Speex2
#ifdef __cplusplus
extern "C" {
#endif
#undef worehov_android_voip_Speex2_DEFAULT_COMPRESSION
#define worehov_android_voip_Speex2_DEFAULT_COMPRESSION 4L
/*
 * Class:     worehov_android_voip_Speex2
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_worehov_android_voip_Speex2_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     worehov_android_voip_Speex2
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_worehov_android_voip_Speex2_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     worehov_android_voip_Speex2
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_worehov_android_voip_Speex2_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint, jint);

/*
 * Class:     worehov_android_voip_Speex2
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_worehov_android_voip_Speex2_encode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint, jint);

/*
 * Class:     worehov_android_voip_Speex2
 * Method:    preprocess
 * Signature: ([S)Z
 */
JNIEXPORT jboolean JNICALL Java_worehov_android_voip_Speex2_preprocess
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     worehov_android_voip_Speex2
 * Method:    echoPlayback
 * Signature: ([S)V
 */
JNIEXPORT jint JNICALL Java_worehov_android_voip_Speex2_echoPlayback
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     worehov_android_voip_Speex2
 * Method:    echoCapture
 * Signature: ([S)V
 */
JNIEXPORT jint JNICALL Java_worehov_android_voip_Speex2_echoCapture
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     worehov_android_voip_Speex2
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_worehov_android_voip_Speex2_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
